#macro TILE_EMPTY_MIN_SCALE 3;
#macro TILE_EMPTY_MAX_SCALE 4;

#macro TILE_CARD_MIN_SCALE 0.5;
#macro TILE_CARD_MAX_SCALE 1;

#macro DEFAULT_DECK_SIZE 60;

#macro FIELD_SIZE_WIDTH 5;
#macro FIELD_SIZE_HEIGHT 5;

#macro PIXEL_DIFFERENCE_BETWEEN_TILES_VERTICAL 25;
#macro PIXEL_DIFFERENCE_BETWEEN_TILES_HORIZONTAL 25;

#macro TILE_EMPTY_WIDTH 10;
#macro TILE_EMPTY_HEIGHT 10;
