#macro TILE_EMPTY_MIN_SCALE 3;
#macro TILE_EMPTY_MAX_SCALE 4;

#macro TILE_EMPTY_SPRITE_WIDTH_OFFSET (((spr_tile.sprite_width * TILE_EMPTY_MIN_SCALE)/2));
#macro TILE_EMPTY_SPRITE_HEIGHT_OFFSET (((spr_tile.sprite_height * TILE_EMPTY_MIN_SCALE)/2));

#macro TILE_CARD_MIN_SCALE 0.5;
#macro TILE_CARD_MAX_SCALE 1;

#macro DEFAULT_DECK_SIZE 60;

#macro FIELD_SIZE_WIDTH 5;
#macro FIELD_SIZE_HEIGHT 5;

#macro PIXEL_DIFFERENCE_BETWEEN_TILES_VERTICAL 10;
#macro PIXEL_DIFFERENCE_BETWEEN_TILES_HORIZONTAL 10;
